config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "home#index"

  resources :contact
  resources :orders
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :items
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  attr_accessor :login

  validates :username,
            :presence => true,
            :uniqueness => {
              :case_sensitive => false
            }

    def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  before_action :authenticate_user!
  def create
    if request.xhr?
      if params[ "airport-from" ]
        TravelMailer.new_inquiry( params[ 'airport-from' ], params[ 'airport-to' ], params[ 'date' ], params[ 'qty' ], params[ 'info' ] ).deliver_now
        render partial:'success', layout: false
      else
        ContactMailer.new_contact( params[ 'name' ], params[ 'email' ], params[ 'body' ] ).deliver_now
        render partial:'success', layout: false
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new( item_params )

    if @item.save
      redirect_to new_item_path order_id: @item.order_id
    end
  end

  def edit
    @item = Item.find_by( id: params[ 'id' ] )

    if request.xhr?
      @item.update_attributes( priority: params[ 'priority' ] )
    end
  end

  def update
    @item = Item.find_by( id: params[ 'id' ] )
    @item.update_attributes( status: params[ 'item' ][ 'status' ] )
    @order = @item.order

    ChangeMailer.new_change( @order ).deliver_now

    redirect_to order_path( @order )
  end

  private

    def item_params
      params.require( :item ).permit( :order_id, :store, :name, :model_number, :status, :priority, :price_range, :shipping_time )
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    @orders = Order.all.sort_by &:created_at
    @orders = @orders.reverse
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new( order_params )

    if @order.save
      redirect_to new_item_path
    end
  end

  def show
    @order = Order.find_by( id: params[ 'id' ] )
    @items = @order.items.sort_by &:created_at
    @items = @items.reverse
  end

  def destroy
    if request.xhr?
      @order = Order.find( params[ 'order' ] )
      @order.items.destroy_all
      @order.destroy
    end
  end

  private

    def order_params
      params.require( :order ).permit( :user_id, :order_number )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/contact/_success.erb
<p>Thank you! Your message has been recorded!</p>

app/views/home/index.erb
<!-- Header -->
	<%= render 'layouts/header' %>

<!-- One -->
	<section id="one" class="wrapper">
		<div class="inner">
			<p>Welcome! You have administrative privilege. Your pricing differs from regular users. You won't see prices. You can just order! U been hooked up fam! - D</p>
			<div class="flex flex-3">
				<article>
					<header>
						<h3>To View Your Orders<br /> <%= link_to 'Click Here', orders_path %></h3>
					</header>
				</article>
				<article>
					<header>
						<h3>To Place An Order<br /> <%= link_to 'Click Here', new_order_path %></h3>
					</header>
				</article>
				<article>
					<header>
						<h3>To Request Something<br /> Send Email Below</h3>
					</header>
				</article>
			</div>
		</div>
	</section>

<!-- Two -->
	<section id="two" class="wrapper style1 special travel-area">
		<div class="inner">
			<header>
				<h2>Travel Inquiry</h2>
				<h3>let us know where you want to go and we'll send you your tickets. you pay us on your time...fam!</h3>
				<p>If you're flying to or from LAX, the tickets are on us!</p>
			</header>

			<form class="contact-form" action="/contact" method="post">
				<div class="form-wrapper-apt">
					<div class="close-in-1">
						<label for="airport-from">Flying From - City:</label>
						<input type="text" name="airport-from">
					</div>

					<br>

					<div class="close-in-2">
						<label for="airport-to">Flying To - City:</label>
						<input type="text" name="airport-to">
					</div>

					<br>

					<div class="close-in-1">
						<label for="date">Date:</label>
						<input type="text" id="datepicker">
					</div>

					<br>

					<div class="close-in-2">
						<label for="qty">People</label>
						<select>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
						</select>
					</div>
				</div>

				<br>

				<label for="info">Please tell us each person's full name, date of birth, and address!</label>
				<textarea name="body" rows="8" cols="80"></textarea>

				<br>

				<input type="submit" value="Submit!" class='travel-click'>
			</form>
			<div class="flex flex-4">
			</div>
		</div>
	</section>


<!-- Three -->
	<section id="two" class="wrapper style1 special change-bgs">
		<div class="inner">
			<header>
				<h2>Send Us A Message</h2>
				<p>we'd love to know how we're doing!</p>
			</header>

			<form class="contact-form" action="/contact" method="post">
				<label for="name">Name</label>
				<input type="text" name="name" value="<%= current_user.name %>">

				<br>

				<label for="email">Email</label>
				<input type="text" name="email" value="<%= current_user.email %>">

				<br>

				<label for="Body">Body</label>

				<textarea name="body" rows="8" cols="80"></textarea>

				<br>

				<input type="submit" value="Submit!" class='contact-click'>
			</form>
			<div class="flex flex-4">
			</div>
		</div>
	</section>

<!-- Footer -->
	<%= render 'layouts/footer' %>

<script type="text/javascript">
	$( 'form input.contact-click' ).on( 'click', function( e ) {
		e.preventDefault();

		var target = e.target
		var url = target.parentElement.action
		var type = target.parentElement.method
		var data = 'name=' + target.parentElement[ 0 ].value +
							 '&email=' + target.parentElement[ 1 ].value +
							 '&body=' + target.parentElement[ 2 ].value

		$.ajax({
			type: type,
			url: url,
			data: data
		}).done( function( response ) {
			$( 'form' ).hide();
			$( '#two div.inner' ).append( response );
		});
	});

	$( 'form input.travel-click' ).on( 'click', function( e ) {
		e.preventDefault();

		var target = e.target
		var url = target.parentElement.action
		var type = target.parentElement.method
		var data = 'airport-from=' + target.parentElement[ 0 ].value +
							 '&airport-to=' + target.parentElement[ 1 ].value +
							 '&date=' + target.parentElement[ 2 ].value +
							 '&qty=' + target.parentElement[ 3 ].value +
							 '&info=' + target.parentElement[ 4 ].value


		$.ajax({
			type: type,
			url: url,
			data: data
		}).done( function( response ) {
			debugger;
			$( '.travel-area form' ).hide();
			$( '.travel-area div.inner' ).append( response );
		});
	});
</script>

app/views/items/edit.erb
<h1><%= @item.name %></h1>
<%= form_for @item do |f| %>
  <%= f.text_field :status %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/items/new.erb
<%= render 'layouts/header' %>

<div class="new-item-form-area">
  <%= form_for @item do |f| %>
  <label for="store">Pick A Store</label>
  <%= f.select :store, [ [ 'TopShop' ], [ 'Lululemon' ], [ 'PacSun' ], [ 'Zara' ], [ 'Century 21' ], [ 'Sea Dreamer The Label' ], [ 'Swimwearworld.com' ], [ 'Crate & Barrel' ], [ 'H&M' ], [ 'Sunglass Hut' ], [ 'Bed Bath & Beyond' ], [ "Victoria's Secret" ] ], { selected: 'TopShop' } %>
  <label for="name">Name - Place Color Into Name of Item As Well!</label>
  <%= f.text_field :name %>
  <%= f.label :model_number %>
  <%= f.text_field :model_number %>
  <label for="price_range">Choose The Price Range For This Item</label>
  <%= f.select :price_range, [ [ '$0 - $50' ], [ '$50 - $100' ], [ '$100 - $150' ], [ '$150 - $250' ], [ '$250 - $500' ], [ '$500 +' ] ] %>
  <%= f.hidden_field :shipping_time, value: 'This item will ship out within 24 hours!', class: "hidden_shipping_time" %>
  <p>This item will ship out within 24 hours!</p>

  <% if params[ 'order_id' ] %>
    <%= f.hidden_field :order_id, value: params[ 'order_id' ] %>
  <% else %>
    <%= f.hidden_field :order_id, value: Order.last.id %>
  <% end %>

  <%= f.submit 'Add Item To Order!', class: "submit-new-item" %>
  <% end %>
</div>

<div class="link-holder">
  <% if Order.last.items.empty? == false %>
  <% if params[ 'order_id' ] %>
  <%= link_to 'View Your Order', order_path( Order.find_by( id: params[ 'order_id' ] ) ), class: :view_making_order %>
  <% else %>
  <%= link_to 'View Your Order', order_path( Order.last ), class: :view_making_order %>
  <% end %>
  <% end %>
</div>

<script type="text/javascript">
  $( 'form #item_price_range' ).on( 'change', function( e ) {
    $('form p').remove();
    var price_range = e.target.value;

    if ( price_range === '$0 - $50' ) {
      var element_yes = e.target.parentElement.lastElementChild
        $(element_yes).before('<p>This item will ship out within 24 hours!</p>');
        $('.hidden_shipping_time').val('This item will ship out within 24 hours!');
    } else if ( price_range === '$50 - $100' ) {
        var element_yes = e.target.parentElement.lastElementChild
          $(element_yes).before('<p>This item will ship out within 24 - 48 hours!</p>');
          $('.hidden_shipping_time').val('This item will ship out within 24 - 48 hours!');
    } else if ( price_range === '$100 - $150' ) {
        var element_yes = e.target.parentElement.lastElementChild
          $(element_yes).before('<p>This item will ship out within 3 - 4 days!</p>');
          $('.hidden_shipping_time').val('This item will ship out within 3 - 4 days!');
    } else if ( price_range === '$150 - $250' ) {
        var element_yes = e.target.parentElement.lastElementChild
          $(element_yes).before('<p>This item will ship out within 3 - 5 days!</p>');
          $('.hidden_shipping_time').val('This item will ship out within 3 - 5 days!');
    } else if ( price_range === '$250 - $500' ) {
        var element_yes = e.target.parentElement.lastElementChild
          $(element_yes).before('<p>This item will ship out within 5 - 7 days!</p>');
          $('.hidden_shipping_time').val('This item will ship out within 5 - 7 days!');
    } else if ( price_range === '$500 +' ) {
        var element_yes = e.target.parentElement.lastElementChild
          $(element_yes).before('<p>This item will ship out within 7 - 10 days!</p>');
          $('.hidden_shipping_time').val('This item will ship out within 7 - 10 days!');
    };
  });
</script>

app/views/layouts/_footer.erb
<div class="footer-foot-bottom">
  
</div>

app/views/layouts/_header.erb
<header id="header">
  <div class="inner">
    <%= link_to 'Home', root_path, class: 'logo' %>
    <nav id="nav">
      <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'logout-link' %>
		</nav>
    <a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
  </div>
</header>

<!-- Banner -->
	<section id="banner">
		<h1>Welcome to Soul Bazaar - <%= current_user.name %></h1>
		<p>A marketplace designed for special people like YOU!</p>
	</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dx871scsd9</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'style', media: 'all' %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'main.js' %>
    <%= javascript_include_tag 'skel.min.js' %>
    <%= javascript_include_tag 'util.js' %>
    <%= javascript_include_tag 'mailers.js' %>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
      $( function() {
        $( "#datepicker" ).datepicker();
      } );
    </script>
  </head>

  <body>
    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/orders/index.erb
<%= render 'layouts/header' %>

<table>
  <tr>
    <th>Order Number</th>
    <th>Status</th>
    <th>Delete</th>
  </tr>

  <% @orders.each do | order | %>
    <tr>
      <td><%= link_to "#{ order.order_number }", order_path( order ) %></td>
      <td><%= order.order_status %></td>
      <td>
        <%= form_for order, html: { method: :delete, class: 'form-delete-order' } do |f| %>
          <%= f.hidden_field :id, value: order.id %>
          <%= f.submit 'Delete', class: 'submit-todo-delete' %>
        <% end %>
      </td>
    </tr>
  <% end %>

</table>

<script type="text/javascript">
  $( '.submit-todo-delete' ).on( 'click', function( e ) {
    e.preventDefault();
    var target = e.target.parentElement;
    var data = "order=" + target[ 3 ].value;
    var url = target.action;

    $.ajax({
      type: 'delete',
      url: url,
      data: data
    }).done( function( response ) {
      location.reload();
    });
  });
</script>

app/views/orders/new.erb
<%= render 'layouts/header' %>

<div class="new-center-order-form">
  <%= form_for @order do |f| %>
    <%= f.hidden_field :order_number, value: rand( 1000..6000000 ).to_s %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit 'Begin Order!' %>
  <% end %>
</div>

app/views/orders/show.erb
<%= render 'layouts/header' %>

<div class="head">
  <h3>Order #<%= @order.order_number %> - <%= @order.order_status %></h3>

  <table id='items-table-full'>
    <col width="70">
    <col width="70">
    <col width="50">
    <col width="100">
    <col width="10">
    <tr>
      <th>Store</th>
      <th>Item Name</th>
      <th>Item Model</th>
      <th>Status</th>
      <th>Priority</th>
    </tr>

    <% @items.each_with_index do | item, idx | %>
    <% if item.status.include?( 'Picked Up!' ) || item.status.include?( 'Delivered!' ) %>
      <tr class='stat-compl'>
    <% elsif item.priority == 'High' %>
      <tr class='high-prio'>
    <% else %>
      <tr class='low-prio'>
    <% end %>
        <td class='we-ft'><%= item.store %></td>
        <td class='we-ft'><%= item.name %></td>
        <td class='we-ft'><%= item.model_number %></td>
        <td class='td-status we-ft'><%= item.status %></td>
        <td class='we-ft'>
          <div class="form-holder">
            <form class="item-priority-form" action="/items/<%= item.id %>/edit" method="patch">
              <select name="priority">
                <% if item.priority == 'Low' %>
                <option value="Low">Low</option>
                <option value="High">High</option>
                <% else %>
                <option value="High">High</option>
                <option value="Low">Low</option>
                <% end %>
              </select>
            </form>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<div class="link-holder">
  <%= link_to "Add To This Order", new_item_path( :order_id => params[ 'id' ] ), class: :add_item_to_order_link %>
</div>


<script type="text/javascript">
  $( '.item-priority-form select' ).on( 'change', function( e ) {
    e.preventDefault();

    var target = e.target;
    var type = target.parentElement.method;
    var url = target.parentElement.action;
    var data = $( target ).serialize();

    $.ajax({
      type: type,
      url: url,
      data: data
    }).done( function( response ) {
        location.reload();
    });
  });
</script>